# Default initial positions for allegro_hand_right's ros2_control fake system

initial_positions:
  joint_0_0: 0
  joint_10_0: 0
  joint_11_0: 0
  joint_12_0: 0
  joint_13_0: 1.57
  joint_14_0: 0
  joint_15_0: 0
  joint_1_0: 0
  joint_2_0: 0
  joint_3_0: 0
  joint_4_0: 0
  joint_5_0: 0
  joint_6_0: 0
  joint_7_0: 0
  joint_8_0: 0
  joint_9_0: 0
