# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_0_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_10_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_11_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_12_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_13_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14
    min_position: -0.1
  joint_14_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_15_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_7_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_8_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_9_0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0
